---
version: "2.0"

endpoints: 
  nodeendpoint-pg:
    kind: ip

services:
  node:
    image: quay.io/vpavlin0/wakash:7023f48
    depends_on:
      - postgres
    expose:
      - port: 60000
        as: 60000
        proto: tcp
        to:
          - global: true
            ip: nodeendpoint-pg

      - port: 8003
        as: 8003
        proto: tcp
        to:
          - global: true
            ip: nodeendpoint-pg

      - port: 9005
        proto: udp
        to:
          - global: true
            ip: nodeendpoint-pg

      - port: 8000
        as: 8000
        proto: tcp
        to:
          - global: true
            ip: nodeendpoint-pg

      - port: 80
        as: 80
        to:
          - global: true
            ip: nodeendpoint-pg
    params:
      storage:
        certs:
          mount: /etc/letsencrypt
    env:
      - DOMAIN=
      - IP_ADDR=
      - NODEKEY=
      - POSTGRES_USER=waku
      - "POSTGRES_PASSWORD=secretpassword"
    args:
      - --relay=true
      - --filter=true
      - --lightpush=true
      - --pubsub-topic=/waku/2/default-waku/proto
      - --pubsub-topic=/waku/2/dev-waku/proto
      - --keep-alive=true
      - --peer-exchange=true
      - --max-connections=300
      - --dns-discovery=true
      - --dns-discovery-url=enrtree://ANEDLO25QVUGJOUTQFRYKWX6P4Z4GKVESBMHML7DZ6YK4LGS5FC5O@prod.wakuv2.nodes.status.im
      - --discv5-discovery=true
      - --discv5-udp-port=9005
      - --discv5-enr-auto-update=True
      - --log-level=DEBUG
      - --metrics-server=True
      - --metrics-server-port=8003
      - --metrics-server-address=0.0.0.0
      - --store=true
      - --store-message-retention-policy=time:2592000

  postgres:
    image: postgres 
    expose:
      - port: 5432
        to:
          - service: node
    params:
      storage:
          data:
              mount: /var/lib/postgresql/
    env:
      - POSTGRES_USER=waku
      - "POSTGRES_PASSWORD=secretpassword"
      - POSTGRES_DB=waku
profiles:
  compute:
    postgres:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - name: data
            size: 5Gi
            attributes:
              persistent: true
              class: beta3
    node:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - name: certs
            size: 100Mi
            attributes:
              persistent: true
              class: beta3


  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        postgres:
          denom: uakt
          amount: 100000
        node: 
          denom: uakt
          amount: 100000

deployment:
  postgres:
    westcoast:
      profile: postgres
      count: 1 
  node:
    westcoast:
      profile: node
      count: 1

