---
version: "2.0"

services:
  chia:
    image: cryptoandcoffee/akash-chia:200
    expose:
      - port: 8080
        as: 80
        proto: tcp
        to:
          - global: true
    env:
    #############################REQUIRED##############################
      - VERSION=1.3.5
     #Always check https://github.com/Chia-Network/chia-blockchain/releases
      - CONTRACT=
      - FARMERKEY=
      - PLOTTER=bladebit-disk
     #Choose your plotter software - madmax, bladebit, bladebit-disk
      - FINAL_LOCATION=local
     #Set to "local" to access finished plots through web interface.
     #Set to "upload" and finished plots will be uploaded to a SSH destination like user@ip:/home/user/plots
      - CPU_UNITS=100
      - MEMORY_UNITS=208Gi
      - STORAGE_UNITS=2000Gi
     #Must match CPU/Memory/Storage units defined in resources.
    #############################OPTIONAL##############################
     #Uncomment the variables below when set FINAL_LOCATION=upload to enable remote uploading
      #- REMOTE_HOST=changeme.com #SSH upload host
      #- REMOTE_LOCATION=changeme #SSH upload location like /root/plots
      #- REMOTE_PORT=22 #SSH upload port
      #- REMOTE_USER=changeme #SSH upload user
      #- REMOTE_PASS=changme #SSH upload password
      #- UPLOAD_BACKGROUND=true
     #Change to true to enable multiple background uploading of plots, this is the best option to use use 100% of your bandwidth.
      - RAMCACHE=198G
      #Used only for PLOTTER=bladebit-disk, you must increase the memory resources requested below with this additional cache size.
      #- RCLONE=false
     #When true must also update JSON_RCLONE and add any destination in same format.
      #- TOTAL_UPLOADS=1000
     #Set the total number of parallel uploads allowed to an rclone destination
      #- ENDPOINT_LOCATION=
     #Only used for RCLONE=true
      #- ENDPOINT_DIR=
     #Only used for RCLONE=true
      #- JSON_RCLONE=
      #  [storj]\n
      #  type = storj\n
      #  api_key = x\n
      #  passphrase = x\n
      #  satellite_address = x@x:7777\n
      #  access_grant = replaceme
     #Example of STORJ config for RCLONE=true.  If you want to use your own endpoint please escape each line with a backslash n, like in the example.
profiles:
  compute:
    chia:
      resources:
        cpu:
          units: 100.0
        memory:
          size: 208Gi
        storage:
          size: 2000Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      attributes:
        chia-plotting: "true"
      pricing:
        chia:
          denom: uakt
          amount: 100000
deployment:
  chia:
    akash:
      profile: chia
      count: 1
